"""remove cc_path and compose_project_name from projects

Revision ID: 7209108afdf5
Revises:
Create Date: 2025-10-17 13:44:52.115248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7209108afdf5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('backend_port', sa.Integer(), nullable=False),
    sa.Column('frontend_port', sa.Integer(), nullable=False),
    sa.Column('postgres_port', sa.Integer(), nullable=False),
    sa.Column('redis_port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('health', sa.String(), nullable=True),
    sa.Column('is_configured', sa.Boolean(), nullable=True),
    sa.Column('repo_count', sa.Integer(), nullable=True),
    sa.Column('tech_count', sa.Integer(), nullable=True),
    sa.Column('task_count', sa.Integer(), nullable=True),
    sa.Column('last_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_stopped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backend_port'),
    sa.UniqueConstraint('frontend_port'),
    sa.UniqueConstraint('postgres_port'),
    sa.UniqueConstraint('redis_port')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
