"""create events table

Revision ID: 7db4424ec6b7
Revises: 7209108afdf5
Create Date: 2025-11-03 17:55:07.328673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db4424ec6b7'
down_revision: Union[str, None] = '7209108afdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: This migration is empty because the events table was already created
    # during Task 2 (commit 417aaf2) via test execution (Base.metadata.create_all).
    #
    # When alembic revision --autogenerate ran, it detected no differences between
    # the metadata and the actual database schema, resulting in an empty migration.
    #
    # The events table DOES exist with the correct schema:
    # - Columns: id, subject, origin, correlation_id, payload, timestamp
    # - Indexes: subject, correlation_id, timestamp (single + composite)
    #
    # This migration maintains proper migration chain but performs no operations.
    # Future: If starting from scratch, drop table and regenerate this migration.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
