server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    timeout: 10s
    batchwait: 1s
    batchsize: 102400

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values:
              - "commandcenter_*"

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'

    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            logger: logger

      # Extract timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano

      # Set labels
      - labels:
          level:
          logger:

  # Backend application logs
  - job_name: backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          service: commandcenter-backend
          __path__: /app/logs/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            module: module
            request_id: request_id
            user_id: user_id

      - timestamp:
          source: timestamp
          format: RFC3339Nano

      - labels:
          level:
          module:

      - output:
          source: message

  # Traefik access logs
  - job_name: traefik
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik
          service: traefik
          __path__: /var/log/traefik/access.log

    pipeline_stages:
      - json:
          expressions:
            client_ip: ClientAddr
            method: RequestMethod
            path: RequestPath
            status: DownstreamStatus
            duration: Duration

      - labels:
          method:
          status:

      - output:
          source: message

  # System logs (optional)
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<app>\S+)(?:\[(?P<pid>\d+)\])?:\s+(?P<message>.*)$'

      - labels:
          app:
          hostname:

      - timestamp:
          source: timestamp
          format: "Jan 02 15:04:05"
