"""Add Phase 7 graph schema

Revision ID: 18d6609ae6d0
Revises: d3e92d35ba2f
Create Date: 2025-11-06 19:30:37.219660

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "18d6609ae6d0"
down_revision: Union[str, Sequence[str], None] = "d3e92d35ba2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_rate_limits_resource_type", table_name="github_rate_limits")
    op.create_index("idx_integrations_enabled", "integrations", ["enabled"], unique=False)
    op.create_index("idx_integrations_status", "integrations", ["status"], unique=False)
    op.drop_constraint("jobs_celery_task_id_key", "jobs", type_="unique")
    op.drop_index("ix_jobs_celery_task_id", table_name="jobs")
    op.create_index(op.f("ix_jobs_celery_task_id"), "jobs", ["celery_task_id"], unique=True)
    op.create_index("idx_jobs_celery_task", "jobs", ["celery_task_id"], unique=False)
    op.drop_index("idx_knowledge_entries_category", table_name="knowledge_entries")
    op.drop_index("idx_knowledge_entries_technology_id", table_name="knowledge_entries")
    op.drop_index("idx_knowledge_entries_vector_db_id", table_name="knowledge_entries")
    op.drop_column("knowledge_entries", "search_mode")
    op.drop_column("knowledge_entries", "kb_document_ids")
    op.drop_column("knowledge_entries", "kb_collection_name")
    op.drop_column("knowledge_entries", "kb_chunk_count")

    # Data migration: Set NULL updated_at to created_at (or NOW if created_at is also NULL)
    op.execute(
        """
        UPDATE projects
        SET updated_at = COALESCE(created_at, NOW())
        WHERE updated_at IS NULL
    """
    )

    op.alter_column("projects", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.drop_index("ix_projects_id", table_name="projects")
    op.drop_index("idx_repositories_language", table_name="repositories")
    op.drop_index("idx_repositories_last_synced_at", table_name="repositories")
    op.drop_index("idx_repositories_owner", table_name="repositories")
    op.drop_index("idx_repositories_owner_name", table_name="repositories")
    op.drop_index("idx_research_tasks_assigned_to", table_name="research_tasks")
    op.drop_index("idx_research_tasks_due_date", table_name="research_tasks")
    op.drop_index("idx_research_tasks_repository_id", table_name="research_tasks")
    op.drop_index("idx_research_tasks_status", table_name="research_tasks")
    op.drop_index("idx_research_tasks_technology_id", table_name="research_tasks")
    op.alter_column(
        "technologies",
        "latency_ms",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="P99 latency in milliseconds",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "throughput_qps",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Throughput in queries per second",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "integration_difficulty",
        existing_type=postgresql.ENUM(
            "trivial", "easy", "moderate", "complex", "very_complex", name="integrationdifficulty"
        ),
        comment=None,
        existing_comment="Estimated integration complexity",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "integration_time_estimate_days",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Estimated integration time in days",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "maturity_level",
        existing_type=postgresql.ENUM(
            "alpha", "beta", "stable", "mature", "legacy", name="maturitylevel"
        ),
        comment=None,
        existing_comment="Technology maturity level",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "stability_score",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Stability score (0-100)",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "cost_tier",
        existing_type=postgresql.ENUM(
            "free", "freemium", "affordable", "moderate", "expensive", "enterprise", name="costtier"
        ),
        comment=None,
        existing_comment="Cost tier category",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "cost_monthly_usd",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Estimated monthly cost in USD",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "dependencies",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="Technology dependencies as JSON",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "alternatives",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Comma-separated list of alternative technology IDs",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "last_hn_mention",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Last HackerNews mention timestamp",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "hn_score_avg",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Average HackerNews story score",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "github_stars",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="GitHub repository star count",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "github_last_commit",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Last GitHub commit timestamp",
        existing_nullable=True,
    )
    op.drop_index("idx_technologies_domain", table_name="technologies")
    op.drop_index("idx_technologies_domain_status", table_name="technologies")
    op.drop_index("idx_technologies_priority_relevance", table_name="technologies")
    op.drop_index("idx_technologies_status", table_name="technologies")
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.alter_column(
        "webhook_deliveries",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.drop_index("idx_webhook_deliveries_config", table_name="webhook_deliveries")
    op.drop_index("idx_webhook_deliveries_event_type", table_name="webhook_deliveries")
    op.drop_index("idx_webhook_deliveries_project", table_name="webhook_deliveries")
    op.drop_index("idx_webhook_deliveries_scheduled", table_name="webhook_deliveries")
    op.drop_index("idx_webhook_deliveries_status", table_name="webhook_deliveries")
    op.create_index(
        op.f("ix_webhook_deliveries_project_id"), "webhook_deliveries", ["project_id"], unique=False
    )
    op.drop_index("idx_webhook_events_event_type", table_name="webhook_events")
    op.drop_index("idx_webhook_events_processed", table_name="webhook_events")
    op.drop_index("idx_webhook_events_repository", table_name="webhook_events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_webhook_events_repository", "webhook_events", ["repository_full_name"], unique=False
    )
    op.create_index("idx_webhook_events_processed", "webhook_events", ["processed"], unique=False)
    op.create_index("idx_webhook_events_event_type", "webhook_events", ["event_type"], unique=False)
    op.drop_index(op.f("ix_webhook_deliveries_project_id"), table_name="webhook_deliveries")
    op.create_index("idx_webhook_deliveries_status", "webhook_deliveries", ["status"], unique=False)
    op.create_index(
        "idx_webhook_deliveries_scheduled", "webhook_deliveries", ["scheduled_for"], unique=False
    )
    op.create_index(
        "idx_webhook_deliveries_project", "webhook_deliveries", ["project_id"], unique=False
    )
    op.create_index(
        "idx_webhook_deliveries_event_type", "webhook_deliveries", ["event_type"], unique=False
    )
    op.create_index(
        "idx_webhook_deliveries_config", "webhook_deliveries", ["config_id"], unique=False
    )
    op.alter_column(
        "webhook_deliveries",
        "payload",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.create_index("idx_technologies_status", "technologies", ["status"], unique=False)
    op.create_index(
        "idx_technologies_priority_relevance",
        "technologies",
        ["priority", "relevance_score"],
        unique=False,
    )
    op.create_index(
        "idx_technologies_domain_status", "technologies", ["domain", "status"], unique=False
    )
    op.create_index("idx_technologies_domain", "technologies", ["domain"], unique=False)
    op.alter_column(
        "technologies",
        "github_last_commit",
        existing_type=postgresql.TIMESTAMP(),
        comment="Last GitHub commit timestamp",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "github_stars",
        existing_type=sa.INTEGER(),
        comment="GitHub repository star count",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "hn_score_avg",
        existing_type=sa.INTEGER(),
        comment="Average HackerNews story score",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "last_hn_mention",
        existing_type=postgresql.TIMESTAMP(),
        comment="Last HackerNews mention timestamp",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "alternatives",
        existing_type=sa.TEXT(),
        comment="Comma-separated list of alternative technology IDs",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "dependencies",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Technology dependencies as JSON",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "cost_monthly_usd",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Estimated monthly cost in USD",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "cost_tier",
        existing_type=postgresql.ENUM(
            "free", "freemium", "affordable", "moderate", "expensive", "enterprise", name="costtier"
        ),
        comment="Cost tier category",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "stability_score",
        existing_type=sa.INTEGER(),
        comment="Stability score (0-100)",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "maturity_level",
        existing_type=postgresql.ENUM(
            "alpha", "beta", "stable", "mature", "legacy", name="maturitylevel"
        ),
        comment="Technology maturity level",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "integration_time_estimate_days",
        existing_type=sa.INTEGER(),
        comment="Estimated integration time in days",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "integration_difficulty",
        existing_type=postgresql.ENUM(
            "trivial", "easy", "moderate", "complex", "very_complex", name="integrationdifficulty"
        ),
        comment="Estimated integration complexity",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "throughput_qps",
        existing_type=sa.INTEGER(),
        comment="Throughput in queries per second",
        existing_nullable=True,
    )
    op.alter_column(
        "technologies",
        "latency_ms",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="P99 latency in milliseconds",
        existing_nullable=True,
    )
    op.create_index(
        "idx_research_tasks_technology_id", "research_tasks", ["technology_id"], unique=False
    )
    op.create_index("idx_research_tasks_status", "research_tasks", ["status"], unique=False)
    op.create_index(
        "idx_research_tasks_repository_id", "research_tasks", ["repository_id"], unique=False
    )
    op.create_index("idx_research_tasks_due_date", "research_tasks", ["due_date"], unique=False)
    op.create_index(
        "idx_research_tasks_assigned_to", "research_tasks", ["assigned_to"], unique=False
    )
    op.create_index("idx_repositories_owner_name", "repositories", ["owner", "name"], unique=False)
    op.create_index("idx_repositories_owner", "repositories", ["owner"], unique=False)
    op.create_index(
        "idx_repositories_last_synced_at", "repositories", ["last_synced_at"], unique=False
    )
    op.create_index("idx_repositories_language", "repositories", ["language"], unique=False)
    op.create_index("ix_projects_id", "projects", ["id"], unique=False)
    op.alter_column("projects", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.add_column(
        "knowledge_entries",
        sa.Column(
            "kb_chunk_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Number of chunks created in KnowledgeBeast",
        ),
    )
    op.add_column(
        "knowledge_entries",
        sa.Column("kb_collection_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "knowledge_entries",
        sa.Column(
            "kb_document_ids",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="List of KnowledgeBeast document IDs for this entry",
        ),
    )
    op.add_column(
        "knowledge_entries",
        sa.Column(
            "search_mode",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="Search mode used: vector, keyword, or hybrid",
        ),
    )
    op.create_index(
        "idx_knowledge_entries_vector_db_id", "knowledge_entries", ["vector_db_id"], unique=False
    )
    op.create_index(
        "idx_knowledge_entries_technology_id", "knowledge_entries", ["technology_id"], unique=False
    )
    op.create_index(
        "idx_knowledge_entries_category", "knowledge_entries", ["category"], unique=False
    )
    op.drop_index("idx_jobs_celery_task", table_name="jobs")
    op.drop_index(op.f("ix_jobs_celery_task_id"), table_name="jobs")
    op.create_index("ix_jobs_celery_task_id", "jobs", ["celery_task_id"], unique=False)
    op.create_unique_constraint("jobs_celery_task_id_key", "jobs", ["celery_task_id"])
    op.drop_index("idx_integrations_status", table_name="integrations")
    op.drop_index("idx_integrations_enabled", table_name="integrations")
    op.create_index(
        "idx_rate_limits_resource_type", "github_rate_limits", ["resource_type"], unique=False
    )
    # ### end Alembic commands ###
