"""add_settings_tables

Revision ID: 9ce77bee762b
Revises: a5de4c7bd725
Create Date: 2025-12-29 17:05:14.955069

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ce77bee762b"
down_revision: Union[str, Sequence[str], None] = "a5de4c7bd725"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("alias", sa.String(length=50), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("api_base", sa.String(length=500), nullable=True),
        sa.Column("api_key_env", sa.String(length=100), nullable=True),
        sa.Column("api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("cost_input", sa.Float(), nullable=False),
        sa.Column("cost_output", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_providers_alias"), "providers", ["alias"], unique=True)
    op.create_table(
        "agent_configs",
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("provider_alias", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["provider_alias"], ["providers.alias"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("role"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_configs")
    op.drop_index(op.f("ix_providers_alias"), table_name="providers")
    op.drop_table("providers")
    # ### end Alembic commands ###
