#!/bin/bash
# CommandCenter Cleanup Script
# Auto-generated by /end-session command
# Removes temporary files and caches

echo "🧹 Starting CommandCenter cleanup..."

# Python cache cleanup
echo "  Cleaning Python cache..."
find . -type d -name "__pycache__" -not -path "*/node_modules/*" -not -path "*/.venv/*" -not -path "*/venv/*" -exec rm -rf {} + 2>/dev/null
find . -type f -name "*.pyc" -delete 2>/dev/null
find . -type f -name "*.pyo" -delete 2>/dev/null
find . -type f -name "*.pyd" -delete 2>/dev/null

# Node.js cache cleanup (frontend)
if [ -d "frontend/node_modules" ]; then
  echo "  Cleaning Node.js cache..."
  rm -rf frontend/.vite 2>/dev/null
  rm -rf frontend/dist 2>/dev/null
  rm -rf frontend/.cache 2>/dev/null
fi

# E2E test artifacts
echo "  Cleaning E2E test artifacts..."
rm -rf test-results/.last-run.json 2>/dev/null
rm -rf playwright-report 2>/dev/null
rm -rf test-results 2>/dev/null

# Temporary files
echo "  Cleaning temporary files..."
find . -type f -name "*.tmp" -delete 2>/dev/null
find . -type f -name "*.log" -not -path "*/node_modules/*" -delete 2>/dev/null
find . -type f -name "*.swp" -delete 2>/dev/null
find . -type f -name "*.swo" -delete 2>/dev/null
find . -type f -name ".DS_Store" -delete 2>/dev/null
find . -type f -name "Thumbs.db" -delete 2>/dev/null

# Empty directories
echo "  Removing empty directories..."
find . -type d -empty -not -path "*/node_modules/*" -not -path "*/.git/*" -delete 2>/dev/null

echo "✅ Cleanup complete!"
