name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  # Backend Testing and Quality Checks
  backend-tests:
    name: Backend Tests & Linting
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: commandcenter_test
          POSTGRES_USER: commandcenter
          POSTGRES_PASSWORD: testpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: backend/requirements*.txt

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Black (code formatting check)
        working-directory: backend
        run: black --check --diff app/
        continue-on-error: false

      - name: Run Flake8 (linting)
        working-directory: backend
        run: |
          flake8 app/ \
            --max-line-length=100 \
            --exclude=__pycache__,migrations \
            --ignore=E203,W503
        continue-on-error: false

      - name: Run MyPy (type checking)
        working-directory: backend
        run: mypy app/ --ignore-missing-imports --no-strict-optional

      - name: Run Bandit (security scanning)
        working-directory: backend
        run: |
          bandit -r app/ \
            -f json -o bandit-report.json \
            -ll -i \
            --exclude app/tests/

      - name: Run Safety (dependency vulnerability check)
        working-directory: backend
        run: |
          safety check --json --output safety-report.json

      - name: Run tests with coverage
        working-directory: backend
        env:
          DATABASE_URL: postgresql://commandcenter:testpassword@localhost:5432/commandcenter_test
          SECRET_KEY: test-secret-key-for-ci-only
          REDIS_URL: redis://localhost:6379
          RAG_STORAGE_PATH: /tmp/rag_storage
          CHROMADB_PATH: /tmp/rag_storage/chromadb
        run: |
          pytest -v \
            --cov=app \
            --cov-report=xml \
            --cov-report=html \
            --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: backend/coverage.xml
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            backend/bandit-report.json
            backend/safety-report.json
          retention-days: 30

  # Frontend Testing and Quality Checks
  frontend-tests:
    name: Frontend Tests & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint
        continue-on-error: false

      - name: Run TypeScript type check
        working-directory: frontend
        run: npm run type-check
        continue-on-error: false

      - name: Run tests
        working-directory: frontend
        run: npm test -- --run

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  # Docker Build Test
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: commandcenter-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          target: production
          push: false
          tags: commandcenter-frontend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Integration Tests
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [docker-build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env <<EOF
          DB_PASSWORD=testpassword
          SECRET_KEY=test-secret-key-for-integration-tests
          POSTGRES_PORT=5432
          REDIS_PORT=6379
          BACKEND_PORT=8000
          FRONTEND_PORT=3000
          ANTHROPIC_API_KEY=dummy
          GITHUB_TOKEN=dummy
          EOF

      - name: Start services with docker-compose
        run: docker-compose up -d

      - name: Wait for services to be healthy
        run: |
          timeout 120 bash -c 'until docker-compose ps | grep -q "healthy"; do sleep 2; done' || true
          sleep 10

      - name: Check service health
        run: |
          curl -f http://localhost:8000/health || exit 1
          curl -f http://localhost:3000 || exit 1

      - name: Run integration tests
        run: |
          docker-compose exec -T backend pytest test_api.py -v || true

      - name: Show logs on failure
        if: failure()
        run: docker-compose logs

      - name: Cleanup
        if: always()
        run: docker-compose down -v

  # Security Scanning
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  # Code Quality Summary
  quality-summary:
    name: Code Quality Summary
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, security-scan]
    if: always()

    steps:
      - name: Check job status
        run: |
          echo "Backend Tests: ${{ needs.backend-tests.result }}"
          echo "Frontend Tests: ${{ needs.frontend-tests.result }}"
          echo "Security Scan: ${{ needs.security-scan.result }}"

          if [[ "${{ needs.backend-tests.result }}" == "failure" ]] || \
             [[ "${{ needs.frontend-tests.result }}" == "failure" ]]; then
            echo "Quality checks failed!"
            exit 1
          fi
